# Generated by Django 5.0.3 on 2024-03-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="tax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentdetail",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentdetail",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash On Delivery", "Cash On Delivery"),
                    ("Khalti", "Khalti"),
                ],
                default="Cash On Delivery",
                max_length=9999,
            ),
        ),
        migrations.AlterField(
            model_name="paymentdetail",
            name="status",
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
