# Generated by Django 5.0.3 on 2024-03-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=999)),
                ("bio", models.TextField()),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=99999, null=True),
                ),
                ("is_bestseller", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=9999)),
                ("slug", models.CharField(max_length=9999, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star_count", models.IntegerField()),
                ("review_text", models.CharField(max_length=400)),
                ("review_media", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=9999)),
                (
                    "sub_slug",
                    models.CharField(
                        blank=True, max_length=9999, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=9999)),
                ("description", models.TextField()),
                (
                    "product_image",
                    models.FileField(
                        blank=True, default="product/Product.jpg", upload_to="product/"
                    ),
                ),
                ("SKU", models.CharField(max_length=9999)),
                (
                    "stock_status",
                    models.CharField(
                        blank=True,
                        choices=[("Instock", "Instock"), ("Outofstock", "Outofstock")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("stock_quantity", models.IntegerField(blank=True, null=True)),
                ("price", models.FloatField()),
                ("published_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("isbn_number", models.CharField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("Nepali", "Nepali"), ("English", "English")],
                        default="English",
                    ),
                ),
                ("top_selling", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=True)),
                ("new_arrival", models.BooleanField(default=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="products", to="product.author"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductQueries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=999)),
                ("answer", models.CharField(max_length=999)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_product",
                        to="product.book",
                    ),
                ),
            ],
        ),
    ]
