# Generated by Django 5.0.3 on 2024-03-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=9999)),
                ("slug", models.CharField(max_length=9999, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=9999)),
                ("author", models.CharField(max_length=9999)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("published_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("isbn_number", models.CharField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("Nepali", "Nepali"), ("English", "English")],
                        default="English",
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
    ]
