# Generated by Django 5.0.3 on 2024-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="new_arrival",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="top_selling",
            field=models.BooleanField(default=False),
        ),
    ]
