# Generated by Django 5.0.3 on 2024-03-25 15:39

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                (
                    "coupon_types",
                    models.CharField(
                        choices=[
                            ("Percentage Discount", "Percentage Discount"),
                            ("Flat Discount", "Flat Discount"),
                            ("Buy One Get One", "Buy One Get One"),
                            ("Free Shipping", "Free Shipping"),
                        ],
                        default="Percentage Discount",
                        max_length=400,
                    ),
                ),
                (
                    "coupon_details",
                    models.JSONField(
                        blank=True,
                        default=product.models.default_coupon_details,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
