# Generated by Django 5.0.3 on 2024-03-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_book_is_used_alter_coupon_coupon_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="review_media",
        ),
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.CharField(blank=True, max_length=9999, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="SKU",
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
