# Generated by Django 5.0.3 on 2024-03-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_review_review_media_author_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="sell_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock_quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock_status",
            field=models.CharField(
                blank=True,
                choices=[("In stock", "In stock"), ("Out of Stock", "Out of Stock")],
                default="In Stock",
                max_length=999,
                null=True,
            ),
        ),
    ]
