# Generated by Django 5.0.3 on 2024-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_book_sell_quantity_alter_book_stock_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.FileField(
                blank=True, default="author/profile.jpg", upload_to="authors/"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="edition",
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn_number",
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                choices=[("Nepali", "Nepali"), ("English", "English")],
                default="English",
                max_length=9999,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock_status",
            field=models.CharField(
                blank=True,
                choices=[("In stock", "In stock"), ("Out of Stock", "Out of Stock")],
                default="In Stock",
                max_length=9999,
                null=True,
            ),
        ),
    ]
